### ISSUE TITLE
string comparison bug

### ISSUE THREAD

**Issue by nickdesaulniers** [imnemo/buffer-factory#1]
so I was looking to use this to solve https://github.com/nickdesaulniers/node-nanomsg/issues/210, but a quick look at https://github.com/imnemo/buffer-factory/blob/099805f4a7e7d6b11d99a264da5270613f286775/index.js#L8 makes me thing that this is completely broken.  Consider this from my node repl:

```
> process.version
'v11.8.0'
> process.version >= "v4.6"
false
> 'a' > 'b'
false
> 'b' > 'a'
true
```

Was this module ever tested pre node v5.10? :man_shrugging:

**Comment by imnemo** [comment]
I have refactor the core code, you can use the latest version of this module, which is `v1.0.5`.

```js
/**
 * For simplicity, there is no params validation check,
 * becuase this util function is only used here .
 * Also, I suppose that versionA and versionB are valid semver string .
 */
function isLargerOrEqual(versionA, versionB) {
  if (versionA === versionB)
    return true;

  var ver1 = versionA.split('.');
  var ver2 = versionB.split('.');

  var len = ver1.length;
  for (var i = 0; i < len; i++) {
    if (ver1[i] === ver2[i] || ver1[i] > ver2[i])
      return true;
  }

  return false;
}
```
